/** @type {import('svgo').Config} */
export default {
	floatPrecision: 3,
	multipass: true,
	js2svg: {
		pretty: true,
		indent: "\t",
	},
	plugins: [
		"removeDoctype",
		"removeXMLProcInst",
		"removeComments",
		"removeMetadata",
		"removeEditorsNSData",
		"cleanupAttrs",
		"mergeStyles",
		"inlineStyles",
		"minifyStyles",
		"cleanupIds",
		"removeUselessDefs",
		"cleanupNumericValues",
		"convertColors",
		"removeUnknownsAndDefaults",
		"removeNonInheritableGroupAttrs",
		"removeUselessStrokeAndFill",
		// "removeViewBox",
		"cleanupEnableBackground",
		"removeHiddenElems",
		"removeEmptyText",
		"convertShapeToPath",
		"convertEllipseToCircle",
		"moveElemsAttrsToGroup",
		"moveGroupAttrsToElems",
		"collapseGroups",
		"convertPathData",
		"convertTransform",
		"removeEmptyAttrs",
		"removeEmptyContainers",
		"removeUnusedNS",
		"mergePaths",
		"sortAttrs",
		"sortDefsChildren",
		"removeTitle",
		"removeDesc",
		// "cleanupListOfValues",
		"convertOneStopGradients",
		"convertStyleToAttrs",
		// "prefixIds",
		"removeDimensions",
		"removeOffCanvasPaths",
		"removeRasterImages",
		// "removeScripts",
		// "removeStyleElement",
		"removeXlink",
		"removeXMLNS",
		// "reusePaths",
		{
			name: "addAttributesToSVGElement",
			params: {
				attributes: [
					{
						xmlns: "http://www.w3.org/2000/svg",
					},
				],
			},
		},
		{
			name: "removeAttributesBySelector",
			params: {
				selector: "[preserveAspectRatio]",
				attributes: ["preserveAspectRatio"],
			},
		},
	],
};
